-- 流程部署
DROP TABLE
IF EXISTS CSV_WF_RE_DEPLOYMENT;

CREATE
OR REPLACE VIEW CSV_WF_RE_DEPLOYMENT AS SELECT
	P.*, D.DEPLOY_TIME_
FROM
	ACT_RE_DEPLOYMENT D,
	ACT_RE_PROCDEF P
WHERE
	D.ID_ = P.DEPLOYMENT_ID_;


-- 流程监控
DROP TABLE
IF EXISTS CSV_WF_HI_MONITORING;

CREATE
OR REPLACE VIEW CSV_WF_HI_MONITORING AS
  SELECT
    RES.*,
    P.NAME_ PROC_DEF_NAME_,
    P.KEY_ PROC_DEF_KEY_,
    P.DEPLOYMENT_ID_,
    HP.BUSINESS_KEY_ PROCESS_BUSINESS_KEY_,
    HP.NAME_ PROC_INST_NAME_
  FROM
    ACT_RU_TASK RES
  INNER JOIN ACT_HI_PROCINST HP ON RES.PROC_INST_ID_ = HP.ID_
  INNER JOIN ACT_RE_PROCDEF P ON P.ID_ = RES.PROC_DEF_ID_;


-- 流程待办列表
DROP TABLE IF EXISTS CSV_WF_RU_TASK;
CREATE OR REPLACE VIEW CSV_WF_RU_TASK AS
  SELECT
    T.*,
    K.USER_ID_,
    K.GROUP_ID_,
    CASE
    WHEN T.ASSIGNEE_ IS NULL OR T.ASSIGNEE_=''
      THEN
        (
          CASE
          WHEN K.USER_ID_ IS NULL
            THEN
              M.USER_ID_
          ELSE
            K.USER_ID_
          END
        )
    ELSE
      T.ASSIGNEE_
    END     TRANSACTOR,
    E.BUSINESS_KEY_
  FROM
    CSV_WF_HI_MONITORING T
    INNER JOIN ACT_RU_EXECUTION E ON T.EXECUTION_ID_ = E.ID_
    LEFT JOIN ACT_RU_IDENTITYLINK K ON K.TASK_ID_ = T.ID_
                                       AND K.TYPE_ = 'candidate'
                                       AND (T.ASSIGNEE_ IS NULL OR T.ASSIGNEE_='')
    LEFT JOIN ACT_ID_MEMBERSHIP M ON M.GROUP_ID_ = K.GROUP_ID_
                                     AND K.USER_ID_ IS NULL
  WHERE
    T.SUSPENSION_STATE_ = 1;



-- 流程已办理列表（历史）
DROP TABLE IF EXISTS CSV_WF_HI_TASK;
CREATE OR REPLACE VIEW CSV_WF_HI_TASK AS
SELECT
	T.*, K.USER_ID_,
	K.GROUP_ID_,
	CASE
WHEN T.ASSIGNEE_ IS NULL OR T.ASSIGNEE_='' THEN
	(
		CASE
		WHEN K.USER_ID_ IS NULL THEN
			M.USER_ID_
		ELSE
			K.USER_ID_
		END
	)
ELSE
	T.ASSIGNEE_
END TRANSACTOR,
 P.NAME_ PROC_DEF_NAME_,
 P.KEY_ PROC_DEF_KEY_,
 HP.BUSINESS_KEY_,
 HP.BUSINESS_KEY_ PROCESS_BUSINESS_KEY_,
 HP.NAME_ PROC_INST_NAME_
FROM
	ACT_HI_TASKINST T
INNER JOIN ACT_HI_PROCINST HP ON HP.ID_ = T.PROC_INST_ID_
INNER JOIN ACT_RE_PROCDEF P ON P.ID_ = T.PROC_DEF_ID_
LEFT JOIN act_hi_identitylink K ON K.TASK_ID_ = T.ID_
AND K.TYPE_ = 'candidate'
AND (T.ASSIGNEE_ IS NULL OR T.ASSIGNEE_='')
LEFT JOIN ACT_ID_MEMBERSHIP M ON M.GROUP_ID_ = K.GROUP_ID_
AND K.USER_ID_ IS NULL
WHERE
	T.DELETE_REASON_ = 'completed';